version: '3.7'

services:
  database_rentx:
    image: postgres
    container_name: database_rentx
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER= #postgres user
      - POSTGRES_PASSWORD= #postgres password
      - POSTGRES_DB= #postgres db
    volumes:
      - pgdata:/data/postgress

  redis:
    image: redis:alpine
    container_name: redis_rentx
    ports:
      - 6379:6379
volumes:
  pgdata:
    driver: local
